### ISSUE TITLE
octal literal in os.chmod?

### ISSUE THREAD

**Issue by lambdaq** [khamidou/lptrace#1]
```
os.chmod(tmp.name, 0666)
os.chmod(fifo_name, 0777)
```

So 0666 === 438 and 0777 == 511 is these two lines intentional or a typo?

**Comment by beardypig** [comment]
*nix file permissions are octal, so this appears to be intentional as well as correct. 
This Wikipedia page has a breakdown, https://en.wikipedia.org/wiki/Chmod#Octal_modes :-)

**Comment by lambdaq** [comment]
@beardypig You are correct. Thanks!
