### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by ajyoon** [khamidou/lptrace#3]
As easy integration with production environments is a concern, this would be much easier to integrate into workflows if it was on PyPI and could be installed with `pip`. Even better would be to have `pip install lptrace` register it such that it can be called from the command line without providing an explicit path to the script (as `pytest` and many others do).

**Comment by khamidou** [comment]
Great point! Fixed: https://pypi.python.org/pypi/lptrace/1.0.0.
