### ISSUE TITLE
Failed to run on macOS

### ISSUE THREAD

**Issue by reorx** [khamidou/lptrace#7]
First of all, thanks for providing this little cool script to help debugging Python programs.

I've been using it successfully on ubuntu server, but when I tried this on my Mac, `sudo python lptrace -p 96365` hanged there and the target program was failed by `segmentation fault`:

```
$ python -m SimpleHTTPServer 10000
Serving HTTP on 0.0.0.0 port 10000 ...
[1]    96365 segmentation fault  python -m SimpleHTTPServer 10000
```

I was using Python 2.7.12 installed by homebrew. My system is OS X 10.11.6.

**Comment by khamidou** [comment]
Hey, thanks for opening this bug! Are you using the stock gdb version? [IIRC you have to jump through some hoops to get it working on MacOS](http://unixnme.blogspot.com/2016/04/how-to-enable-gdb-on-mac-os-x-el-capitan.html).

**Comment by khamidou** [comment]
Closing because of no replies.
